<?php
echo $args['before_widget'];
if ( ! empty( $title ) ) {
	echo $args['before_title'] . __( $title, 'site-statistics' ) . $args['after_title'];
}
echo _e( 'Number of topics in this forum:  ', 'site-statistics' ) . $counter_topics . '<br/>';
echo _e( 'Number of messages in this forum:  ', 'site-statistics' ) . ( $counter_topics + $counter_children ) . '<br/>';
echo _e( 'Number of posts in all blogs multisite:  ', 'site-statistics' ) . $posts_count . '<br/>';

//get the number of users online
if ( bp_has_members( $members_args ) ) {
	echo _e( 'Users online:  ', 'site-statistics' );
	$flag = true;
	while ( bp_members() ) {
		bp_the_member();
		$user_id     = bp_get_member_user_id();
		$member_name = bp_core_get_username( $user_id );
		if ( $flag ) {
			echo $member_name;
			$flag = false;
		} else {
			echo ', ' . $member_name;
		}
	}
	echo '<br/>';
} else {
	echo _e( 'There are no users currently online', 'site-statistics' ) . '<br/>';
}
echo $args['after_widget'];